apiVersion: v1
kind: Secret
metadata:
  name: my-github-oauth-secret
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # Goes with an OAuth app at https://github.com/organizations/CervTest/settings/applications/2226972
  # Take values from GitHub then Base64 encode and paste here
  # Raw to base64: echo -n "abcde" | base64
  github-oath-client-secret: secret
