# This ingress is specific to Argo support for AppSets, which may need an additional hook/API URL exposed (TODO: Confirm)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-appset-ingress
  #labels:
    #app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    #app.kubernetes.io/instance: {{ .Release.Name | quote }}
    #helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: "nginx"
  rules:
  - host: argocdhook.cmdbee.org
    http:
      paths:
      - path: /api/webhook
        pathType: Prefix
        backend:
          service:
            name:  terargo-argocd-applicationset-controller
            port:
              number: 7000
  tls:
  - hosts:
    - argocdhook.cmdbee.org
    secretName: argocd-appset-ingress
