sonarqube:
  elasticsearch:
    bootstrapChecks: false
    configureNode: false
  nginx:
    enabled: false
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/rewrite-target: /
    className: ""
    defaultBackend:
      enabled: false
    hosts:
    - name: sonarqube.terasology.io
    routerPath: /
    sonarqubePath: /
    tls:
    - hosts:
      - sonarqube.terasology.io
      secretName: sonarqube-tls-secret
  livenessProbe:
    initialDelaySeconds: 180
  readinessProbe:
    initialDelaySeconds: 180
  startupProbe:
    initialDelaySeconds: 180
