apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  nodeSelector:
    builder: heavy
  containers:
  - name: my-container
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
  tolerations:
  - key: "heavy-builder-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
