apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-ghost
  namespace: argocd
spec:
  generators:
  - scmProvider:
      cloneProtocol: https
      github:
        organization: CervTest
        tokenRef:
          secretName: my-github-secret
          key: token
      filters:
      - pathsExist: [ghost.marker]
  template:
    metadata:
      name: '{{ repository }}'
    spec:
      source:
        repoURL: '{{ url }}'
        targetRevision: HEAD
        path: .
        helm:
          valueFiles:
          - values.yaml
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ repository }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
