apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app-argocd
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  cm-app-argocd.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: terargo-argocd
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/MovingBlocks/Logistics.git'
        path: argocd
        targetRevision: main
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
