# See readme for how to generate and maintain this list
jenkins:
  controller:
    installLatestPlugins: false
    installPlugins:
      - "analysis-model-api:latest"
      - "antisamy-markup-formatter:latest"
      - "apache-httpcomponents-client-4-api:latest"
      - "authentication-tokens:latest"
      - "basic-branch-build-strategies:latest"
      - "bootstrap5-api:latest"
      - "bouncycastle-api:latest"
      - "branch-api:latest"
      - "caffeine-api:latest"
      - "checks-api:latest"
      - "cloudbees-folder:latest"
      - "command-launcher:latest"
      - "commons-lang3-api:latest"
      - "commons-text-api:latest"
      - "configuration-as-code:latest"
      - "copyartifact:latest"
      - "credentials-binding:latest"
      - "credentials:latest"
      - "data-tables-api:latest"
      - "discord-notifier:latest"
      - "display-url-api:latest"
      - "durable-task:latest"
      - "echarts-api:latest"
      - "extra-columns:latest"
      - "font-awesome-api:latest"
      - "forensics-api:latest"
      - "git-client:latest"
      - "git-forensics:latest"
      - "git:latest"
      - "github-api:latest"
      - "github-branch-source:latest"
      - "github-checks:latest"
      - "github-oauth:latest"
      - "github:latest"
      - "groovy:latest"
      - "htmlpublisher:latest"
      - "http_request:latest"
      - "instance-identity:latest"
      - "ionicons-api:latest"
      - "jackson2-api:latest"
      - "jakarta-activation-api:latest"
      - "jakarta-mail-api:latest"
      - "javadoc:latest"
      - "javax-activation-api:latest"
      - "javax-mail-api:latest"
      - "jaxb:latest"
      - "jdk-tool:latest"
      - "jjwt-api:latest"
      - "job-dsl:latest"
      - "jquery3-api:latest"
      - "junit:latest"
      - "kubernetes-cli:latest"
      - "kubernetes-client-api:latest"
      - "kubernetes-credentials:latest"
      - "kubernetes:latest"
      - "label-linked-jobs:latest"
      - "mailer:latest"
      - "matrix-project:latest"
      - "metrics:latest"
      - "mina-sshd-api-common:latest"
      - "mina-sshd-api-core:latest"
      - "okhttp-api:latest"
      - "permissive-script-security:latest"
      - "pipeline-build-step:latest"
      - "pipeline-gitstatuswrapper:latest"
      - "pipeline-graph-analysis:latest"
      - "pipeline-groovy-lib:latest"
      - "pipeline-input-step:latest"
      - "pipeline-model-api:latest"
      - "pipeline-model-definition:latest"
      - "pipeline-model-extensions:latest"
      - "pipeline-rest-api:latest"
      - "pipeline-stage-step:latest"
      - "pipeline-stage-tags-metadata:latest"
      - "pipeline-stage-view:latest"
      - "pipeline-utility-steps:latest"
      - "plain-credentials:latest"
      - "plugin-util-api:latest"
      - "prism-api:latest"
      - "scm-api:latest"
      - "script-security:latest"
      - "snakeyaml-api:latest"
      - "ssh-credentials:latest"
      - "sshd:latest"
      - "structs:latest"
      - "templating-engine:latest"
      - "thinBackup:latest"
      - "token-macro:latest"
      - "trilead-api:latest"
      - "variant:latest"
      - "view-job-filters:latest"
      - "warnings-ng:latest"
      - "workflow-api:latest"
      - "workflow-basic-steps:latest"
      - "workflow-cps:latest"
      - "workflow-durable-task-step:latest"
      - "workflow-job:latest"
      - "workflow-multibranch:latest"
      - "workflow-scm-step:latest"
      - "workflow-step-api:latest"
      - "workflow-support:latest"
