jenkins:
  agent:
    # This archetype agent gets used to inherit values but also serves as a standard builder
    podName: kaniko-precached-jdk11
    # Note that an additional "terajenkins-jenkins-agent" label gets added everywhere (podLabels thing?)
    customJenkinsLabels: "kaniko-precached-jdk11 ts-engine ts-module lib heavy light java11 light-java"
    nodeUsageMode: "EXCLUSIVE"
    sideContainerName: builder
    image: terasology/jenkins-precached-agent
    tag: latest-jdk11
    command: "/bin/sh -c"
    args: "cat"
    # This is needed for some reason or the controller refuses to connect this agent?
    TTYEnabled: true
    # Set resources for additional agents to inherit
    resources:
      requests:
        cpu: 1250m
        memory: "6144Mi"
      limits:
        cpu: 1750m #Saw this spike to nearly 4 for a Terasology engine build PR
        memory: "8192Mi" #Note: Saw a Terasology engine build spike memory to 9.96 GB! It really would be nice to have multi-stage with diff agents if truly optimizing ... mostly 6.2-6.4

  additionalAgents:
    kanikoEight:
      podName: kaniko-precached-jdk8
      customJenkinsLabels: "kaniko-precached-jdk8"
      tag: latest-jdk8

    kanikoSeventeen:
      podName: kaniko-precached-jdk17
      customJenkinsLabels: "kaniko-precached-jdk17 java17"
      tag: latest-jdk17

    javaNative:
      podName: java-native
      customJenkinsLabels: "java-native"
      image: terasology/java-native-jnlp
      tag: latest

    kubectl:
      podName: kubectl-agent-experimental
      customJenkinsLabels: "java-native"
      image: cervator/pre-cached-jenkins-agent
      tag: experimental

    pythonBuilder:
      podName: python-agent
      customJenkinsLabels: "python"
      image: terasology/modulesite
      tag: latest

    androidBuilder:
      podName: android-agent
      customJenkinsLabels: "android"
      sideContainerName: jnlp
      image: terasology/jenkins-android-agent
      tag: latest
      command: '""'
      args: "${computer.jnlpmac} ${computer.name}"

    # For building other images using Kaniko (the kaniko-something agents are _output_ from such)
    kanikoBuilder:
      podName: kaniko
      customJenkinsLabels: "kaniko"
      sideContainerName: kaniko
      image: "gcr.io/kaniko-project/executor"
      tag: debug
      command: "/busybox/sleep"
      args: "infinity"
      resources:
        requests:
          cpu: 256m
          memory: "4Gi"
        limits:
          cpu: 900m
          memory: "8Gi"
