jenkins:
  controller:
    JCasC:
      configScripts:
        agents: |
          jenkins:
            clouds:
            - kubernetes:
                name: "kubernetes"
                containerCap: 10
                containerCapStr: "10"
                websocket: true

                templates:

                  # TODO: Rebuild atop latest inbound solely using jnlp container rather than an extra
                  # For native builds of some of our libraries
                  - name: "java-native"
                    label: "java-native"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: builder
                      image: "terasology/java-native-jnlp:latest"
                      command: "sleep"
                      args: "infinity"
                      resourceRequestCpu: "1"
                      resourceRequestMemory: "6144Mi"
                      resourceLimitCpu: "1750m"
                      resourceLimitMemory: "8192Mi"

                  # NOTE: Seems outdated - https://registry.hub.docker.com/r/terasology/modulesite was built from a GitHub repo
                  # now redirecting to https://github.com/MovingBlocks/movingblocks.github.com which uses a GitHub action instead
                  # For our module site and other web stuff
                  - name: "python-agent"
                    label: "python"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: builder
                      image: "terasology/modulesite:latest"
                      command: "sleep"
                      args: "infinity"
                      resourceRequestCpu: "250m"
                      resourceRequestMemory: "2048Mi"
                      resourceLimitCpu: "750m"
                      resourceLimitMemory: "4096Mi"

                  # TODO: Rebuild atop latest inbound solely using jnlp container rather than an extra (and remove DS default container declaration)
                  # Android builds for Gestalt and Destination Sol
                  - name: "android-agent"
                    label: "android"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: builder
                      image: "terasology/jenkins-android-agent:latest"
                      command: "sleep"
                      args: "infinity"
                      resourceRequestCpu: "750m"
                      resourceRequestMemory: "4864Mi"
                      resourceLimitCpu: "1750m"
                      resourceLimitMemory: "8192Mi"

                  # For building our own custom Docker images (without the less secure use of Docker-in-Docker)
                  - name: "kaniko"
                    label: "kaniko"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: kaniko
                      image: "gcr.io/kaniko-project/executor:debug"
                      command: "/busybox/sleep"
                      args: "infinity"
                      resourceRequestCpu: "250m"
                      resourceRequestMemory: "4Gi"
                      resourceLimitCpu: "900m"
                      resourceLimitMemory: "8Gi"

                  # For Backstage and Docker stuff - has two different containers
                  - name: "node20-and-dind"
                    label: "node20 docker"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: jnlp  # Use "jnlp" as the container name as this image relies on its own Jenkins config
                      image: "ghcr.io/felipecrs/jenkins-agent-dind:sha-56f739d"
                      privileged: true  # Add privileged mode for docker-in-docker (not great for security but eh)
                      resourceRequestCpu: "250m"
                      resourceRequestMemory: "2Gi"
                      resourceLimitCpu: "750m"
                      resourceLimitMemory: "5Gi"
                    - name: node # An added utility container includes node 20
                      image: "node:20"
                      command: "sleep"
                      args: "infinity"
                      resourceRequestCpu: "250m"
                      resourceRequestMemory: "2Gi"
                      resourceLimitCpu: "1250m"
                      resourceLimitMemory: "5Gi"

                  # For utility Kubernetes & GCloud
                  - name: "gcloud-cli"
                    label: "gcloud kubectl"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: utility
                      image: "gcr.io/google.com/cloudsdktool/google-cloud-cli:504.0.1"
                      command: "sleep"
                      args: "infinity"
                      resourceRequestCpu: "125m"
                      resourceRequestMemory: "2048Mi"
                      resourceLimitCpu: "250m"
                      resourceLimitMemory: "4096Mi"

                  # New multi-JDK pre-cached Java agents taking over from old approach with one image per JDK (although only 8 and 11 need extra steps)
                  - name: "pre-cached-jdk8"
                    label: "java8"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: jnlp  # Override the default Jenkins container with our extended image
                      image: "us-east1-docker.pkg.dev/teralivekubernetes/logistics/precachedagent:latest"
                      resourceRequestCpu: "800m"
                      resourceRequestMemory: "2.5Gi"
                      resourceLimitCpu: "1750m"
                      resourceLimitMemory: "5Gi"
                      envVars: # Allow Jenkins agent process to use its own JDK while configuring a different one for general purpose
                      - envVar:
                          key: "JENKINS_JAVA_BIN"
                          value: "/opt/java/openjdk/bin/java"
                      - envVar:
                          key: "JAVA_HOME"
                          value: "/opt/jdk8u432-b06"
                      - envVar:
                          key: "PATH" # Note: Trying to prepend the existing var by including :$PATH broke the Jenkins agent connection process - hard coding instead
                          value: "/opt/jdk8u432-b06/bin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin"

                  # Note that "lib", "light" and "light-java" label jobs tend to be an old generation from back when the JDK was not explicitly called out - leave those on JDK 11 for now
                  - name: "pre-cached-jdk11"
                    label: "lib light java11 light-java"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: jnlp  # Override the default Jenkins container with our extended image
                      image: "us-east1-docker.pkg.dev/teralivekubernetes/logistics/precachedagent:latest"
                      resourceRequestCpu: "800m"
                      resourceRequestMemory: "2.5Gi"
                      resourceLimitCpu: "1750m"
                      resourceLimitMemory: "5Gi"
                      envVars: # Allow Jenkins agent process to use its own JDK while configuring a different one for general purpose
                      - envVar:
                          key: "JENKINS_JAVA_BIN"
                          value: "/opt/java/openjdk/bin/java"
                      - envVar:
                          key: "JAVA_HOME"
                          value: "/opt/jdk-11.0.25+9"
                      - envVar:
                          key: "PATH" # Note: Trying to prepend the existing var by including :$PATH broke the Jenkins agent connection process - hard coding instead
                          value: "/opt/jdk-11.0.25+9/bin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin"

                  - name: "pre-cached-jdk17"
                    label: "ts-module java17"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: jnlp  # Override the default Jenkins container with our extended image
                      image: "us-east1-docker.pkg.dev/teralivekubernetes/logistics/precachedagent:latest"
                      resourceRequestCpu: "800m"
                      resourceRequestMemory: "2.5Gi"
                      resourceLimitCpu: "1750m"
                      resourceLimitMemory: "5Gi"
                    # Tolerate but do not require a node from the secondary node pool with more resources (toleration only) - improves availability for mainline stuff
                    yaml: |
                      apiVersion: v1
                      kind: Pod
                      spec:
                        tolerations:
                        - key: "heavy-builder-only"
                          operator: "Equal"
                          value: "true"
                          effect: "NoSchedule"

                  - name: "pre-cached-jdk17-heavy"
                    label: "ts-engine ts-module heavy java17"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: jnlp  # Override the default Jenkins container with our extended image
                      image: "us-east1-docker.pkg.dev/teralivekubernetes/logistics/precachedagent:latest"
                      resourceRequestCpu: "1"
                      resourceRequestMemory: "6144Mi"
                      resourceLimitCpu: "1750m"
                      resourceLimitMemory: "8192Mi"
                    # Require a node from the secondary node pool with more resources (toleration AND node selector)
                    yaml: |
                      apiVersion: v1
                      kind: Pod
                      spec:
                        nodeSelector:
                          builder: heavy
                        tolerations:
                        - key: "heavy-builder-only"
                          operator: "Equal"
                          value: "true"
                          effect: "NoSchedule"

                  # For reference and testing this is a vanilla default Jenkins build agent that just comes with its JDK 17 and nothing else
                  - name: "default17"
                    label: "default17"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                    - name: "jnlp"
                      image: "jenkins/inbound-agent:latest-jdk17"
                      alwaysPullImage: true
                      resourceRequestCpu: "800m"
                      resourceRequestMemory: "6144Mi"
                      workingDir: "/home/jenkins/agent"
