# terawekan: # This is needed if using the arent chart, as we subchart the target apps - but not if applying tese values directly to the app chart
ingress:
  enabled: true
  hosts:
    - wekan.terasology.io
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  tls:
  - secretName: wekan-tls-secret
    hosts:
      - wekan.terasology.io
endpoint: wekan.terasology.io
root_url: https://wekan.terasology.io
mongodb-replicaset:
  replicas: 1
resources:
  requests:
    memory: 256Mi
    cpu: 300m
  limits:
    memory: 1Gi
    cpu: 500m
